version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
#         environment:
#           FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 62:b3:b1:c1:7d:56:af:06:db:9b:26:70:98:e2:da:23
      - run:
          name: Setup Virtual VM to compile the code 
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            . helloworld/bin/activate
            pyinstaller -F hello_world.py
            docker build -t $docker_user/$IMAGE_NAME:$TAG .
            echo $docker_pass | docker login -u $docker_user --password-stdin
            docker push $docker_user/$IMAGE_NAME:$TAG
  deploy: 
    docker:
      - image: "$docker_user/$IMAGE_NAME:$TAG"
    steps:
      - run:
          name: Deploy app to Linux Server where docker is installed 
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@52.207.136.246 "/bin/bash ./deploy_app.sh $docker_user/$IMAGE_NAME:$TAG"
workflows: 
  version: 2
  commit-workflow:
      jobs:
        - build
        - deploy 
  # schedule-workflow:
  #     triggers:
  #       - schedule:
  #          cron: "0 * * * *"
  #          filters:
  #            branches: 
  #              only:
  #                - master 
  #     jobs:
  #       - build
  #       - deploy 


