version: 2.1
executors:
  managed-circleci-executer:
    docker:
      - image: circleci/python:latest
commands:
  hello:
    steps:
      - run: checkout
      - run: echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run: echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
      - run: virtualenv helloworld
      - run: . helloworld/bin/activate
      - run: pip install --no-cache-dir -r requirements.txt
      - run: . helloworld/bin/activate
      - run: pyinstaller -F hello_world.py
      - run: docker build -t $docker_user/$IMAGE_NAME:$TAG .
      - run: echo $docker_pass | docker login -u $docker_user --password-stdin
      - run: docker push $docker_user/$IMAGE_NAME:$TAG
jobs:
  build:
    executor: managed-circleci-executer
    steps:
    #  - checkout
       - run: 
            command:  hello
       - setup_remote_docker:
          docker_layer_caching: false
  deploy: 
    executor: managed-circleci-executer
    steps:
      - run:
          name: Deploy app to Linux Server where docker is installed 
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@52.207.136.246 "/bin/bash ./deploy_app.sh $docker_user/$IMAGE_NAME:$TAG"
workflows: 
  version: 2
  commit-workflow:
      jobs:
        - build
        - hold:
            type: approval
            requires: 
            - build
        - deploy:
            requires:
            - hold

  # schedule-workflow:
  #     triggers:
  #       - schedule:
  #          cron: "0 * * * *"
  #          filters:
  #            branches: 
  #              only:
  #                - master 
  #     jobs:
  #       - build
  #       - deploy 


